### ISSUE TITLE
Setting gas limit & detecting "Out of Gas" for Solidity Contract deployment

### ISSUE THREAD

**Issue by GFJHogue** [ethers-io/ethers.io#12]
Hi Richard!

1. When deploying a larger contract, the default gas limit sometimes doesn't make the cut. Allowing users to set it would be nice.

2. If a deploy transaction runs out of gas during contract creation [(example)](https://ropsten.etherscan.io/tx/0x55e29a856c525944a04d12a86e78ad68c04f354cbde8308f9c2cd938ed646fc8), it still shows as successfully deployed on ethers.io.

**Comment by ricmoo** [comment]
The old Solidity compiler has been deprecated and now this just uses the normal Remix IDE (using the Web3 Bridge). The new Ethers Container is much smarter at choosing a gas limit as well, so this should be fixed.

Thanks!
