### ISSUE TITLE
where to download `ethers`?

### ISSUE THREAD

**Issue by qx133** [ethers-io/ethers.io#3]
in your tutorial 

> /Users/ethers/test-application> ethers init

where can the program `ethers` be downloaded?

**Comment by ricmoo** [comment]
Oh wow, you're eager. :)

I didn't realize I'd committed that version of the documentation already. It really isn't ready yet, in a few more days the tutorial and command-line tool will be ready though.

If you really want to check it out though, there is a slightly old version on npm,, `npm install -g ethers-cli`.

**Comment by qx133** [comment]
haha, wanted to try out porting over https://eth.codetract.io

**Comment by ricmoo** [comment]
The `ethers` tool is now `ethers-build` and can be installed using:

```
/Users/ethers> npm install -g ethers-cli
```

The documentation is still evolving, but can be found at: https://docs.ethers.io/ethers-app/html/dev-cli.html

There is also a new library we're releasing this week that will go a long way in easing integration. :)
