### ISSUE TITLE
Chrome is not wokring

### ISSUE THREAD

**Issue by harryyuanfeng** [ethers-io/ethers.io#8]
At this time, Chrome is not working. But safari will work. Just let everyone knows and hope Richard will fix it.

**Comment by Alaradia** [comment]
no it works on chrome at least on windows

**Comment by harryyuanfeng** [comment]
Oh we have two mac users and Chrome not working on both of our macs.

**Comment by ricmoo** [comment]
I believe all the Chrome related bugs have been fixed. There were some changes in how Chrome allows connections without certain headers specified.
