### ISSUE TITLE
Wallet.fromBrainWallet doesn't work

### ISSUE THREAD

**Issue by Manidos** [ethers-io/ethers.io#9]
Hey! Let me start off with saying that `ethers.io` is truly amazing. I've just started learning it and love it already. 
Browser: Chrome 58.0.3029.110
OS: Windows Vista 64 bit

When I run this code the browser dev console starts logging random numbers every ~500ms starting from a small number, like 0.00000123123123123.   Each new logged number is larger that the previous one. The logging goes on until the number is 1 (it takes ~30 seconds). Then promise resolves and I get in the console: `Address: [object Object]`. Sad.
 
```
import * as ethers from 'ethers'
class EthersService {
  constructor () {
    this.Wallet = ethers.Wallet
    this.createBrainWallet()
  }
  createBrainWallet () {
    const username = 'support@ethers.io'
    const password = 'password123'
    this.Wallet.fromBrainWallet(username, password, (result) => console.log(result))
      .then((wallet) => console.log('Address: ' + wallet))
      .catch((error) => console.log('error', error))
  }
}
const ethersService = new EthersService()
```

**Comment by ricmoo** [comment]
That logged number is the percent complete (between 0 and 1) that is completed for the generation of the wallet.

If you don't want/need it, don't pass in a callback. Or at least don't console.log(result) in your callback.

**Comment by ricmoo** [comment]
Also, it doesn't return an address, it returns an instance of a wallet. So, wallet.address will be the address, wallet.privateKey, etc.

**Comment by Manidos** [comment]
@ricmoo, Oh, just noticed I put  plus sign here `console.log('Address: ' + wallet)`. That's why I wasn't getting an object in the console. Sorry, for this. Anyway, thank you!

**Comment by Manidos** [comment]
@ricmoo, I'm sorry to bother you, but is it normal that the wallet creating using this method takes ~45s? Is there a way to speed things up?
